title:             Omoikane
email:             omoikane.shin@gmail.com
description:       あるがままに
author:            Omoikane
baseurl:           "/prophecy"
# url:               "https://omoikane-shin.github.io"

# Social Profiles
twitter_username:  omoikane_shin
github_username:   omoikane-shin
facebook_username: omoikane.shin

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
