title:             Omoikane
email:             omoikane.shin@gmail.com
description:       あるがままに
author:            Omoikane
baseurl:           "/prophecy"
# url:               "https://omoikane-shin.github.io"

# Social Profiles
twitter_username:  omoikane_shin
github_username:   omoikane-shin
facebook_username: omoikane.shin

# Build settings
permalink: /:year/:month/:day/:title/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

